version: "3"

networks:
  issues:
    driver: bridge

services:
  issue568-eureka:
    image: issue568-eureka:0.1
    ports:
      - "8761:8761"
    networks:
      - issues
  issue568-gateway:
    image: issue568-gateway:0.1
    environment:
      - EUREKA_HOST=issue568-eureka
    ports:
      - "9000:9000"
    networks:
      - issues
  issue568-micronaut:
    image: issue568-micronaut:0.1
    environment:
      - EUREKA_HOST=issue568-eureka
      - MICRONAUT_SERVER_HOST=issue568-micronaut
    depends_on:
      - issue568-eureka
#    ports:
#      - "8080:8080"
    networks:
      issues:
        aliases:
          - ISSUE568-MICRONAUT
  zookeeper:
    image: zookeeper:3.3
    networks:
      issues:
        aliases:
        - zookeeper
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    #image: wurstmeister/kafka:1.0.1
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - ZOOKEEPER_CONNECTION_TIMEOUT_MS=180000
      - KAFKA_CREATE_TOPICS=notifications:1:1
    networks:
      issues:
        aliases:
        - kafka
