micronaut:
    application:
        name: issue568-micronaut
    server:
        port: 8080

eureka:
    client:
        registration:
            enabled: true
            fail-fast: false
            retry-count: 8
            retry-delay: 5s
        defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"
